[build]
  command = "npm run build:library"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.ts"
  [headers.values]
    Content-Type = "application/javascript"

